modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL = "https://github.com/Peeko32213/OpposingForce/issues"

[[mods]]
    modId = "opposing_force"
    version = "1.0.0"
    logoFile = "logo.png"
    itemIcon = "minecraft:spider_eye"
    configBackground = "minecraft:textures/block/stone.png"
    authors = "Unusual Modding"
    credits = "Peeko32213, Indominator, Scouter456, AbsoluteKun, IcyDwarf, platypushasnohat"
    displayURL = "https://github.com/Peeko32213/OpposingForce"
    displayName = "Opposing Force"
    description = '''A Mod that expands the enemy variety in Minecraft!'''

[[dependencies.opposing_force]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,1.20.2]"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.opposing_force]]
	modId = "forge"
	mandatory = true
	versionRange = "[47.1.3,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.opposing_force]]
	modId = "geckolib"
	mandatory = true
	versionRange = "[4.2,)"
	ordering = "BEFORE"
	side = "BOTH"