modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL = "https://github.com/Peeko32213/OpposingForce/issues"

[[mods]]
    modId = "opposing_force"
    version = "1.0.0"
    logoFile = "logo.png"
    itemIcon = "minecraft:spider_eye"
    configBackground = "minecraft:textures/block/stone.png"
    authors = "Unusual Modding"
    credits = "Peeko32213, Indominator, Scouter456, AbsoluteKun, IcyDwarf, platypushasnohat"
    displayURL = "https://github.com/Peeko32213/OpposingForce"
    displayName = "Opposing Force"
    description = '''A Mod that expands the enemy variety in Minecraft!'''

[[dependencies.opposing_force]] #optional
	modId="forge" #mandatory
	mandatory=true #mandatory
	versionRange="${forge_version_range}" #mandatory
	ordering="NONE"
	side="BOTH"
[[dependencies.opposing_force]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"
[[dependencies.opposing_force]]
	modId="geckolib"
	mandatory=true
	versionRange="[4.2,)"
	ordering="BEFORE"
	side="BOTH"