modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "opposing_force"
version = "1.0"
logoFile = "opposing_force.png"
authors = "Unusual Modding"
displayName = "Opposing Force"
description = '''
A Mod that expands the enemy variety in Minecraft!'''

[[dependencies.opposing_force]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opposing_force]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21]"
ordering = "NONE"
side = "BOTH"