modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "opposing_force"
    version = "${file.jarVersion}"
    logoFile = "opposing_force.png"
    authors = "Unusual Modding"
    displayName = "Opposing Force"
    description = '''
    Adds a ton of new enemies to fight!
    '''

[[dependencies.opposing_force]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.opposing_force]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"